# Generated by Django 2.2.3 on 2019-08-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190827_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='orden',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
